// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleIAMV1
import GoogleGax

extension Clients {
  protocol ContainerAnalysisStub: Sendable {
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func getVulnerabilityOccurrencesSummary(
      request: GetVulnerabilityOccurrencesSummaryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContainerAnalysisV1.VulnerabilityOccurrencesSummary

    func exportSbom(
      request: ExportSBOMRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudContainerAnalysisV1.ExportSBOMResponse
  }
}
