// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleIAMV1
import GoogleCloudGax

/// Retrieves analysis results of Cloud components such as Docker container
/// images. The Container Analysis API is an implementation of the
/// [Grafeas](https://grafeas.io) API.
///
/// Analysis results are stored as a series of occurrences. An `Occurrence`
/// contains information about a specific analysis instance on a resource. An
/// occurrence refers to a `Note`. A note contains details describing the
/// analysis and is generally stored in a separate project, called a `Provider`.
/// Multiple occurrences can refer to the same note.
///
/// For example, an SSL vulnerability could affect multiple images. In this case,
/// there would be one note for the vulnerability and an occurrence for each
/// image with the vulnerability referring to that note.
///
/// @Snippet(path: "ContainerAnalysisQuickstart")
public class ContainerAnalysisClient: Clients.ContainerAnalysisProtocol {
  let inner: any Clients.ContainerAnalysisStub

  /// Creates a new `ContainerAnalysisClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ContainerAnalysisStub = try Clients.ContainerAnalysisTransport(options)
    inner = Clients.ContainerAnalysisRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ContainerAnalysisLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Sets the access control policy on the specified note or occurrence.
  /// Requires `containeranalysis.notes.setIamPolicy` or
  /// `containeranalysis.occurrences.setIamPolicy` permission if the resource is
  /// a note or an occurrence, respectively.
  ///
  /// The resource takes the format `projects/[PROJECT_ID]/notes/[NOTE_ID]` for
  /// notes and `projects/[PROJECT_ID]/occurrences/[OCCURRENCE_ID]` for
  /// occurrences.
  ///
  /// @Snippet(path: "ContainerAnalysis_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a note or an occurrence resource.
  /// Requires `containeranalysis.notes.setIamPolicy` or
  /// `containeranalysis.occurrences.setIamPolicy` permission if the resource is
  /// a note or occurrence, respectively.
  ///
  /// The resource takes the format `projects/[PROJECT_ID]/notes/[NOTE_ID]` for
  /// notes and `projects/[PROJECT_ID]/occurrences/[OCCURRENCE_ID]` for
  /// occurrences.
  ///
  /// @Snippet(path: "ContainerAnalysis_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns the permissions that a caller has on the specified note or
  /// occurrence. Requires list permission on the project (for example,
  /// `containeranalysis.notes.list`).
  ///
  /// The resource takes the format `projects/[PROJECT_ID]/notes/[NOTE_ID]` for
  /// notes and `projects/[PROJECT_ID]/occurrences/[OCCURRENCE_ID]` for
  /// occurrences.
  ///
  /// @Snippet(path: "ContainerAnalysis_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Gets a summary of the number and severity of occurrences.
  ///
  /// @Snippet(path: "ContainerAnalysis_GetVulnerabilityOccurrencesSummary")
  public func getVulnerabilityOccurrencesSummary(
    request: GetVulnerabilityOccurrencesSummaryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContainerAnalysisV1.VulnerabilityOccurrencesSummary {
    try await self.inner.getVulnerabilityOccurrencesSummary(request: request, options: options)
  }

  /// Generates an SBOM for the given resource.
  ///
  /// @Snippet(path: "ContainerAnalysis_ExportSBOM")
  public func exportSbom(
    request: ExportSBOMRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContainerAnalysisV1.ExportSBOMResponse {
    try await self.inner.exportSbom(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ContainerAnalysisClient`.
  ///
  /// To mock `ContainerAnalysisClient` change your functions to receive
  /// `some ContainerAnalysisProtocol` or `any ContainerAnalysisProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ContainerAnalysisProtocol {
    /// See `ContainerAnalysisClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `ContainerAnalysisClient.setIamPolicy`.
    func setIamPolicy(
      resource: Swift.String,
      policy: GoogleIAMV1.Policy?,
    ) async throws -> GoogleIAMV1.Policy

    /// See `ContainerAnalysisClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `ContainerAnalysisClient.getIamPolicy`.
    func getIamPolicy(
      resource: Swift.String,
    ) async throws -> GoogleIAMV1.Policy

    /// See `ContainerAnalysisClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `ContainerAnalysisClient.testIamPermissions`.
    func testIamPermissions(
      resource: Swift.String,
      permissions: [Swift.String],
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `ContainerAnalysisClient.getVulnerabilityOccurrencesSummary`.
    func getVulnerabilityOccurrencesSummary(request: GetVulnerabilityOccurrencesSummaryRequest)
      async throws -> GoogleCloudContainerAnalysisV1.VulnerabilityOccurrencesSummary

    /// See `ContainerAnalysisClient.getVulnerabilityOccurrencesSummary`.
    func getVulnerabilityOccurrencesSummary(
      parent: Swift.String,
      filter: Swift.String,
    ) async throws -> GoogleCloudContainerAnalysisV1.VulnerabilityOccurrencesSummary

    /// See `ContainerAnalysisClient.exportSbom`.
    func exportSbom(request: ExportSBOMRequest) async throws
      -> GoogleCloudContainerAnalysisV1.ExportSBOMResponse

    /// See `ContainerAnalysisClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `ContainerAnalysisClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `ContainerAnalysisClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `ContainerAnalysisClient.getVulnerabilityOccurrencesSummary`.
    func getVulnerabilityOccurrencesSummary(
      request: GetVulnerabilityOccurrencesSummaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerAnalysisV1.VulnerabilityOccurrencesSummary

    /// See `ContainerAnalysisClient.exportSbom`.
    func exportSbom(
      request: ExportSBOMRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContainerAnalysisV1.ExportSBOMResponse
  }
}

// Default implementations
extension Clients.ContainerAnalysisProtocol {
  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(
    resource: Swift.String,
    policy: GoogleIAMV1.Policy?,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.SetIamPolicyRequest().with {
      $0.resource = resource
      $0.policy = policy
    }
    return try await self.setIamPolicy(request: request)
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(
    resource: Swift.String,
  ) async throws -> GoogleIAMV1.Policy {
    let request = GoogleIAMV1.GetIamPolicyRequest().with {
      $0.resource = resource
    }
    return try await self.getIamPolicy(request: request)
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(
    resource: Swift.String,
    permissions: [Swift.String],
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    let request = GoogleIAMV1.TestIamPermissionsRequest().with {
      $0.resource = resource
      $0.permissions = permissions
    }
    return try await self.testIamPermissions(request: request)
  }

  public func getVulnerabilityOccurrencesSummary(request: GetVulnerabilityOccurrencesSummaryRequest)
    async throws -> GoogleCloudContainerAnalysisV1.VulnerabilityOccurrencesSummary
  {
    try await self.getVulnerabilityOccurrencesSummary(request: request, options: .init())
  }

  public func getVulnerabilityOccurrencesSummary(
    request: GetVulnerabilityOccurrencesSummaryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContainerAnalysisV1.VulnerabilityOccurrencesSummary {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getVulnerabilityOccurrencesSummary(
    parent: Swift.String,
    filter: Swift.String,
  ) async throws -> GoogleCloudContainerAnalysisV1.VulnerabilityOccurrencesSummary {
    let request = GetVulnerabilityOccurrencesSummaryRequest().with {
      $0.parent = parent
      $0.filter = filter
    }
    return try await self.getVulnerabilityOccurrencesSummary(request: request)
  }

  public func exportSbom(request: ExportSBOMRequest) async throws
    -> GoogleCloudContainerAnalysisV1.ExportSBOMResponse
  {
    try await self.exportSbom(request: request, options: .init())
  }

  public func exportSbom(
    request: ExportSBOMRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudContainerAnalysisV1.ExportSBOMResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
